transcription_apis/whisperx_api.py

This is just a small change to print the whisper model from `config` rather than `self.model`. Model prints its memory address I think. I checked the available attributes and none of them returns the actual model name. Printing from config seems to be the only option here.

print model from config

---

EXAMPLE.config
keyboard_handler.py
soundfx.py

For people who want to use other hotkeys that have conflicting native functionality. Enabled by default because I think it's safe to assume that most users don't want their AlwaysReddy hotkeys to simultaneously trigger other stuff.
Only added support for Windows since pynput does not seem to support key suppression.

Add config option to suppress native hotkey functionality (Windows only)

---

main.py

When the user clears the history, last_message_was_cut_off should reset to False so the AI doesn't get told that it was cut off in the next fresh conversation, since it doesn't know what was said previously anyway.

Reset last_message_was_cut_off on clear_messages()

---

config_default.py
main.py

`config.HOTKEY_DELAY` exists already, which I assume was meant to control the double tap delay for activating the clipboard injection, but it has not actually been implemented.
This pull request renames it to `config.RECORD_HOTKEY_DELAY` and implements it. The default value has been changed to what the double tap logic already used (0.2s), so the default behaviour remains the same.

Add record hotkey double tap delay option

---

keyboard_handler.py

No longer needed with the new config loader.

Remove getattr from keyboard_handler

---

README.md
config_default.py
keyboard_handler.py
main.py

This pull request adds a few input-related features and fixes:
- Support for held hotkeys (add_held_hotkey()).
- RECORD_HOTKEY can alternatively be held down to record until it is released (push-to-talk).
- The time the hotkey waits to detect a double tap for clipboard usage no longer delays when the recording start, making it more reponsive.
- Support for unbound hotkeys (set to None). Both the new hotkeys are set to None by default. Unbound hotkeys will not be listed in the terminal.
- Fixes to pynput (Linux/Mac).
- Support overlapping hotkeys: Can bind Shift+Ctrl+R to one thing and Shift+R to another, and then trigger the first without also triggering the second.
- Support for many more keys like Space, Capslock, Esc, F-keys, etc.
PynputHandler has been largely rewritten, because to …

Push-to-talk + pynput fixes

---

input_apis/autohotkey_handler.py
input_apis/input_handler.py
input_apis/keyboard_library_handler.py
input_apis/pynput_handler.py
main.py
requirements.txt

- keyboard_handler has been refactored into a module named input_apis, where each api is a self-contained file. Changed word 'keyboard' to 'input' since AutoHotkey has mouse support, which should be added to pynput_handler as well.
- Implemented [AutoHotkey wrapper](https://github.com/spyoungtech/ahk) as a more reliable replacement to the keyboard package on Windows. (Thanks to @j4byers)
- AutoHotkey uses very different hotkey syntax, for example instead of `ctrl+shift+r` it does `+^r`. So I wrote a hotkey string conversion function so we can keep using the same old hotkey style. Needs more testing.
- The AutoHotkey package is added to requirements.txt with `sys_platform == 'win32'` to only install on Windows.

Input refactor + AutoHotkey handler for Windows

---

TTS_apis/piper_tts_client.py
config_default.py

Some models of Piper have multiple voices built into them, so to support that I added a PIPER_VOICE_INDEX integer option to config.
The option defaults to 0. If a non-zero value is used for a single-voice model, it uses the only voice that exists anyway.

Add config option PIPER_VOICE_INDEX to support multi-voice piper models

---

config_default.py
llm_apis/ollama_client.py

Add keep-alive support for Ollama. This can be useful for creating headless personal assistant where a constant memory usage is not a issue.

add keep-alive support for ollama

---

TTS_apis/piper_tts_client.py
config_default.py

Piper supports controlling the rate of its speech with `--length_scale` (which scales the length of phonemes), where a lower value results in faster speech, and vice versa.
I've added that as a config.py option.

Add PIPER_VOICE_LENGTH to support adjusting the speed of Piper's speech

---

main.py

Fixes the bug from 803459a09c1a8201968c998088d1b5b16a1be292 where you can't run the program if you set RECORD_HOTKEY to a single key (no modifiers).

Fix error when using single-key record hotkey

---

config_default.py
main.py
prompt.py
system_prompts/chat_prompt.py
system_prompts/default_prompt.py

- Added support for loading different system prompts than the default.
- Improved the default system prompt.
- Added a new alternative system prompt that focuses on conversation.
prompt.py's `prompts` list has been replaced with a get_initial_prompt() function that takes a prompt name as argument: the ACTIVE_PROMPT config option. The options for that is based on the file names within the system_prompts folder. The nested type of structure with `"default_prompt":{"description":"PLACEHOLDER", "messages":`, was removed since it was unused.
Currently, system_prompts contains two prompt files: **default_prompt.py** and **chat_prompt.py**. Therefore, the valid options for ACTIVE_PROMPT is `"default_prompt"`, or `"chat_prompt"`. If a user creates their own prompt file like **custom_prompt.py**, …

Support for alternative system prompts + New system prompts

---

config_default.py
main.py

For those who might want it, I added a bool option for always including the clipboard content (defaults to False).
To reduce the risk of the AI chattering about the clipboard content when the user asks about something else, I also edited the passed-along text to include `(ignore if user doesn't mention it)`, which makes a clear improvement for Llama 3 8B.

Add ALWAYS_INCLUDE_CLIPBOARD option

---

config_default.py

Change the default config clipboard START_SEQ and END_SEQ to `"[CLIPSTART]"` and `"[CLIPEND]"` for better reliability.
To find this, I ran multiple styles through a benchmark of 20 different questions repeated 200 times for each style.
Model: Llama 3 8B
| START_SEQ | END_SEQ | Success rate (%) |
| --------- | ------- | ---------------- |
| -CLIPSTART- | -CLIPEND- | 82.5% (current default) |
| CLIPSTART | CLIPEND | 94% |
| #CLIPSTART | #CLIPEND | 92% |
| [CLIPSTART] | [CLIPEND] | **96.5%** (best) |
| \<CLIPSTART\> | \<CLIPEND\> | 93.5% |
| \<clipboard\> | \</clipboard\> | 87% |
"Success rate" is measured by how often the AI correctly wraps information within the START_SEQ and END_SEQ tags when asked to copy to clipboard.
Results:  `[CLIPSTART]` and `[CLIPEND]` is the most reliable style on …

More reliable START_SEQ and END_SEQ defaults

---

README.md

Adding the following to the bottom of **How to**:
1. Navigate to the *system_prompts* directory.
2. Make a copy of an existing prompt file.
3. Open the copy in a text or code editor and edit the prompt inside the two `'''` as you like.
4. Edit your config.py file by setting the `ACTIVE_PROMPT` option to the name of your new prompt file (without the .py extension) as a string.
- For example, if your new prompt file is *custom_prompt.py*, then set in config.py: `ACTIVE_PROMPT = "custom_prompt"`

Add to README: How to make a custom system prompt

---

main.py
prompt.py
system_prompts/chat_prompt.py
system_prompts/default_prompt.py

Update the system prompt before generating responses, so that if a variable (such as date and time) is used in the system prompt, it will be kept up to date.
`prompt.get_initial_prompt()` was also renamed to `prompt.build_initial_messages()` to more accurately reflect its purpose. 
`prompt.get_system_prompt_message()` was added that only returns the system prompt message string, which `prompt.build_initial_messages()` now uses.
`prompt.get_system_prompt_message()` is also used directly in `handle_response()` to refresh the first entry content of `self.messages` instead of rebuilding `self.messages` entirely.
Additionally, both built-in system prompts (**default_prompt** and **chat_prompt**) was updated to include the current date and time. I benchmarked it with Llama 3.1 8B, and it does …

Dynamic system prompt

---

config_default.py
config_loader.py

Proper fix for https://github.com/ILikeAI/AlwaysReddy/issues/74.
In other words, we can have options like OLLAMA_KEEP_ALIVE commented out in the default_config.py without that breaking anything as long as the user correctly uncomments it in his config.py when using Ollama.

Support config.py containing options that config_default.py does not

---

transcription_apis/faster_whisper_client.py

The CTranslate2 [quantization options docs](https://opennmt.net/CTranslate2/quantization.html#quantize-on-model-loading) mentions:
> auto: use the fastest computation type that is supported on this system and device
This is a valid option for faster-whisper's `compute_type` parameter, meaning it will automatically pick between `float16` and `int8`. AlwaysReddy currently always uses float16 for GPU inference, which in many cases is not the optimal pick.
On my GPU, using `auto` almost halves the amount of VRAM that faster-whisper consumes, leaving more room for other things.

Automatic optimal compute type selection for faster-whisper

---

actions/always_reddy_voice_assistant/main.py
actions/example_action/main.py
actions/transcribe_and_paste/main.py
config_default.py
main.py

Unbound hotkeys
---
Before the actions system, all hotkeys could be set to None to unbind them. But now, setting some of them to None cause exceptions. This fixes that.
Verbosity
---
More initial prints are now hidden with `verbose = False`, making the program initialization more succinct. Besides debugging, there is no reason to categorize the bindings by action when there are only five in total.
Let's compare:
```
Setting up AlwaysReddy...
Initializing action: AlwaysReddyVoiceAssistant
Voice assistant hotkeys:
'alt+ctrl+r': Start/stop talking to voice assistant (press to toggle on and off or hold-release)
Hold down 'alt+ctrl' and double tap 'r' to send clipboard content to AlwaysReddy
'alt+ctrl+w': New chat for voice assistant
Initializing action: ReadClipboard
'ctrl+alt+c': To read the …
```

Support for all hotkeys to be None, plus minor clean-up

---

actions/always_reddy_voice_assistant/main.py
completion_manager.py
config_default.py
llm_apis/anthropic_client.py
llm_apis/groq_client.py
llm_apis/lm_studio_client.py
llm_apis/ollama_client.py
llm_apis/openai_client.py
llm_apis/openrouter_client.py
llm_apis/perplexity_client.py
llm_apis/tabbyapi_client.py
llm_apis/togetherai_client.py

This allows users to tweak the parameters like temperature, repeat penalty, etc., of all the clients from this new option:
```py
COMPLETION_PARAMS = {"temperature": 0.7, "max_tokens": 2048}
```
The two default arguments there are the same that were hardcoded in all clients before except Ollama, which was using its own default temperature of 0.8 instead. I kept them so that most users shouldn't notice any difference in their assistant's behaviour.
It's worth noting that the different clients do not have identical sets of parameters. For example, most use "max_tokens" to define the maximum length of the response, but Ollama's equivalent of that is "num_predict". The user will have to look up a list of available parameters for their API of choice.
I have only tested that the params work on …

Add LLM API params option to config

---

soundfx.py

Addresses an issue from #85 where the user would get an error every time the soundfx class tried to play a sound, due to lack of support for mono channel audio devices.
Also early return for zero volume sounds to avoid unnecessary processing if user has set any of the volume options in config to zero.

Support mono audio devices in soundfx

---

config_default.py
llm_apis/ollama_client.py

This pull request does two things:
- Support OLLAMA_KEEP_ALIVE without s/m/h suffix, like "-1" for indefinite or "30" for thirty seconds. Just in case of user error.
- In case an invalid value is used, print a clear warning about it instead of the elusive "STATUS CODE 400" exception, and loads the model indefinitely as a fallback.

Support OLLAMA_KEEP_ALIVE without time suffix + Exception handling

---

README.md
config_default.py
prompt.py
system_prompts/chat_prompt.py
system_prompts/default_prompt.py
system_prompts/modules/clipboard.py
system_prompts/modules/time.py
system_prompts/modules/window_title.py

Modular System Prompt
---
I have separated the clipboard instructions and the date/time fetching of the default_prompt into two separate "modules". Users can from config.py select what combination of these to include, while the default_prompt.py and chat_prompt.py now only focus on the basic behavioural instructions.
Just like with the prompt files, users can very easily add new modules by copying and editing an existing one in the `system_prompts\modules` directory. Then include it by appending their new file to the new config.py option:
```py
ACTIVE_PROMPT_MODULES = ["clipboard", "time", "window_title", "user_custom_module"]
```
Window Title Module
---
I also made a entirely new module that give the assistant the name of the currently focused window title. This often includes relevant …

Modular System Prompt + Option to let assistant see current window title
